name: web3dart_builders
description: Extension of the web3dart package that includes the dart contract generator from abi.
version: 0.0.1
repository: https://github.com/inveker/web3dart_builders
homepage: https://github.com/inveker/web3dart_builders

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.3.1
  code_builder: ^4.3.0
  web3dart: ^2.4.1
  built_collection: ^5.1.1
  path: ^1.8.2
  dart_style: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  build_config: ^1.1.0
  test:
  build_test:

flutter:

