name: web3dart_builders
description: Extension of the web3dart package that includes the dart contract generator from abi.
version: 3.0.1
repository: https://github.com/inveker/web3dart_builders
homepage: https://github.com/inveker/web3dart_builders

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.5.4
  code_builder: ^4.10.1
  built_collection: ^5.1.1
  path: ^1.9.1
  dart_style: ^2.2.4
  wallet: ^0.0.17
  web3dart: ^3.0.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.26.2
  build_runner: ^2.5.4
  build_config: ^1.1.2
  build_test: ^3.2.1
